import{s as p,r as m}from"./assets/keyConstsLS-e1ae3af3.js";import{i as y,a as b}from"./assets/vendor-8cce9181.js";const L={titleColor:"#FFFFFF",messageColor:"#FFFFFF",messageSize:"20px",position:"topRight",displayMode:"replace",closeOnEscape:!0,pauseOnHover:!1,maxWidth:432,messageSize:"20px",messageLineHeight:"24px"};function d(t){y.show({message:t,backgroundColor:"#EF4040",progressBarColor:"#FFE0AC",...L})}const k="https://books-backend.p.goit.global",f=1e3*30,l=b.create({baseURL:k,timeout:f});function h(t){return d(t.message),null}l.interceptors.response.use(t=>t,h);function E(){return l.get("/books/category-list").then(t=>t.data)}function C(){return l.get("/books/top-books").then(t=>t.data)}function T(t){return l.get("/books/category",{params:{category:t}}).then(e=>e.data)}const c={ulCategoryContainer:document.querySelector("#listContainer"),gallery:document.querySelector(".js-gallery")};function v({list_name:t}){return`<li class="item-category"> <button type="button" data-category="${t}">${t}</button></li>`}async function F(){try{const e=(await E()).map(v).join("");c.ulCategoryContainer.insertAdjacentHTML("beforeend",e)}catch(t){console.error("Error rendering Category list",t)}}F();function B(t){const a=t.split(" ");let o="",r=0;for(const s of a){const n=s.length;if(r+n+1>20){o+="...";break}o+=s+" ",r+=n+1}return o.trim()}function g(t){const{_id:e,book_image:a,title:o,author:r}=t;return`
<li class="books-item" data-id=${e}>
<div class="book-wrapper">
 <img class="book-image" src="${a}" alt="${r} ${o}"/>
          <p class="book-image-message-text">QUICK VIEW</p>
</div>
        <h2 class="book-title">${B(o)}</h2>
        <p class="book-author">${r}</p>
</li>     
  `}function S({list_name:t,books:e}){const a=document.createElement("li");a.classList.add("category-books-item");const o=document.createElement("h3");o.classList.add("category-title"),o.textContent=t;const r=document.createElement("ul");r.classList.add("category-list"),r.innerHTML=e.map(g).join(""),r.addEventListener("click",i=>console.log("click"));const s=document.createElement("div");s.classList.add("category-div");const n=document.createElement("button");return n.classList.add("category-button"),n.setAttribute("type","button"),n.setAttribute("data-category",t),n.textContent="SEE MORE",n.addEventListener("click",i=>console.log(i.target.dataset)),a.append(o),a.append(r),a.append(s),s.append(n),a}function u(t){const e=t.split(" "),a=`<span>${e.pop()}</span>`;e.push(a);const o=document.createElement("h1");return o.classList.add("title"),o.innerHTML=e.join(" "),o}async function x(){const t=await C();c.gallery.innerHTML="";const e=t.map(S),a=document.createElement("ul");a.classList.add("category-books-list"),a.append(...e),c.gallery.append(u("Best Sellers Books")),c.gallery.append(a)}async function A(t){c.gallery.innerHTML="";try{const e=await T(t),a=u(t);c.gallery.appendChild(a);const o=document.createElement("ul");o.classList.add("selected-category-list"),c.gallery.appendChild(o);const r=e.map(s=>g(s)).join("");o.innerHTML=r,o.addEventListener("click",()=>console.log("Hello World"))}catch{d("Error rendering category. Please try again later.")}}function M(){document.querySelectorAll("button[data-category]").forEach(e=>e.classList.remove("active"))}const{categoryName:H}=m;function N(t){if(t.target.nodeName!=="BUTTON")return;M(),t.target.classList.add("active");const e=t.target.getAttribute("data-category");p(H,e),e==="All categories"?x():A(e)}const{ulCategoryContainer:$}=c;$.addEventListener("click",N);
//# sourceMappingURL=commonHelpers.js.map
